services:
  backend:
    container_name: youtube-notes-backend
    build:
      context: ./apps/backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@youtube-notes-db:5432/youtube_notes
      - GEMINI_API_KEY=AIzaSyAcA5IM2OM9020yyXjfxCdORZ4ezD7GRmk
      - GEMINI_MODEL=gemini-2.5-flash-lite
      - DEEPGRAM_API_KEY=83478c3f403528651abe06f6024063e39ce5d5d7
      - DEEPGRAM_MODEL=nova-3
    depends_on:
      youtube-notes-db:
        condition: service_healthy
    networks:
      - youtube-notes-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend:
    container_name: youtube-notes-frontend
    build:
      context: ./apps/frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PUBLIC_BACKEND_URL=http://localhost:8000
      - VITE_PUBLIC_TANSTACK_STALE_TIME=300000
      - VITE_PUBLIC_TANSTACK_GARBAGE_COLLECTION_TIME=300000
      - VITE_PUBLIC_API_TIMEOUT=10000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - youtube-notes-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  youtube-notes-db:
    container_name: youtube-notes-db
    build: ./apps/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youtube_notes
    ports:
      - "5432:5432"
    volumes:
      - youtube-notes-db-data:/var/lib/postgresql/data
    networks:
      - youtube-notes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  youtube-notes-network:
    driver: bridge

volumes:
  youtube-notes-db-data:
    driver: local
